name: Create Release

on:
  push:    
    tags:
      - 'v*' 

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  release_project:
    name: Release tela de login
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Downlod content
        uses: actions/download-artifact@v2
        with:
          name: Upload content
      - name: Archive content
        uses: thedoctor0/zip-release@master
        with: 
          filename: site.zip
      - name: Create GitHub Release
        id: create_release  
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
        tag_name: v${{ github.ref }}
        release_name: Release V${{ github.ref }}
      - name: Upload assets GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.upload_url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.ref }}.zip
          asset_content_type: app/zip

  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: Upload content
        uses: actions/upload-artifact@v2
        